# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqldoc < Formula
  desc "SQL documentation and code generation tool"
  homepage "https://github.com/elliots/sqldoc"
  version "0.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elliots/sqldoc/releases/download/v0.0.10/sqldoc_darwin_amd64.tar.gz"
      sha256 "4d4a860cd55a460496d0300d5bf6b60e0f00f21400773754acf5bfcd7f5ddc33"

      define_method(:install) do
        bin.install "sqldoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elliots/sqldoc/releases/download/v0.0.10/sqldoc_darwin_arm64.tar.gz"
      sha256 "4656bf6572f28de19a68e52cf73fc6bb706a09b66d989135d53420f902537fc2"

      define_method(:install) do
        bin.install "sqldoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliots/sqldoc/releases/download/v0.0.10/sqldoc_linux_amd64.tar.gz"
      sha256 "de082878db9e88c7b4031414e65b95b3c24adca4cfb8aec16f42d79e96f86402"
      define_method(:install) do
        bin.install "sqldoc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliots/sqldoc/releases/download/v0.0.10/sqldoc_linux_arm64.tar.gz"
      sha256 "c32d0087e9fb06ccea38ce67b6bd152bf7a986166abd4e3e34ff6866c9208ed1"
      define_method(:install) do
        bin.install "sqldoc"
      end
    end
  end

  test do
    system "#{bin}/sqldoc", "--version"
  end
end
