# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqldoc < Formula
  desc "SQL documentation and code generation tool"
  homepage "https://github.com/elliots/sqldoc"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elliots/sqldoc/releases/download/v0.0.3/sqldoc_darwin_amd64.tar.gz"
      sha256 "8f07683001e975063558a12cc9bfcff143b1239ed2301bcec57b7f5f12485298"

      define_method(:install) do
        bin.install "sqldoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elliots/sqldoc/releases/download/v0.0.3/sqldoc_darwin_arm64.tar.gz"
      sha256 "dc6f7a43c79df75d4066742f2954265c1ec6262a50ae4b18eb28140224f44bc9"

      define_method(:install) do
        bin.install "sqldoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliots/sqldoc/releases/download/v0.0.3/sqldoc_linux_amd64.tar.gz"
      sha256 "7dacd88aa913ba06bc493830fa686273bf3e864709a17d043be8e3737b948ed5"
      define_method(:install) do
        bin.install "sqldoc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliots/sqldoc/releases/download/v0.0.3/sqldoc_linux_arm64.tar.gz"
      sha256 "4fde169696eec372aec5d64540b534ab09a70ac636ac43fbc0e05757ef7e40b4"
      define_method(:install) do
        bin.install "sqldoc"
      end
    end
  end

  test do
    system "#{bin}/sqldoc", "--version"
  end
end
