# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqldoc < Formula
  desc "SQL documentation and code generation tool"
  homepage "https://github.com/elliots/sqldoc"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elliots/sqldoc/releases/download/v0.0.2/sqldoc_darwin_amd64.tar.gz"
      sha256 "85bd872b9e6d40f20fde74d4af205dab74d4cc015ba0989225d44dedcd373e8c"

      define_method(:install) do
        bin.install "sqldoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elliots/sqldoc/releases/download/v0.0.2/sqldoc_darwin_arm64.tar.gz"
      sha256 "d90d6343729d248b35c47850e2dbaf54941c019e68c98b555730a14b7e7727a4"

      define_method(:install) do
        bin.install "sqldoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliots/sqldoc/releases/download/v0.0.2/sqldoc_linux_amd64.tar.gz"
      sha256 "54a0ad7f505ceecb1d81d62357f26122faf1ad28449b8e5dab7b46ebca3e56fa"
      define_method(:install) do
        bin.install "sqldoc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliots/sqldoc/releases/download/v0.0.2/sqldoc_linux_arm64.tar.gz"
      sha256 "08b5b3ab31b9e927f6e6cee6770b9d15931a318d9a10cba864f11402f83af6ed"
      define_method(:install) do
        bin.install "sqldoc"
      end
    end
  end

  test do
    system "#{bin}/sqldoc", "--version"
  end
end
